// auth actions
export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
export const ERROR_SIGNUP_ALERT = 'ERROR_SIGNUP_ALERT';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL ';
export const FORGOT_PASSWORD_SUCCESSFUL = 'FORGOT_PASSWORD';
export const ERROR_FORGOT_PASSWORD_ALERT = 'ERROR_FORGOT_PASSWORD_ALERT';
export const ERROR_LOGIN_ALERT = 'INVALID_LOGIN';
export const ERROR_RESET_PASSWORD_ALERT = 'ERROR_RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESSFUL = 'RESET_PASSWORD_SUCCESSFUL';
// misc actions
export const REQUEST_PENDING = "REQUEST_PENDING";
